name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Run test over the merged changes
        run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            HEAD_SHA=$(git log --oneline | head -n1 | awk '{print $3}')
            git checkout $GITHUB_BASE_REF
            git merge --no-commit --no-edit $HEAD_SHA
            yarn
            yarn lerna run build
            yarn test 
        if: github.event_name == 'pull_request'

      - name: Test
        run: |
          yarn lerna run build
          yarn test
        if: github.event_name != 'pull_request'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3