name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Run test over the merged changes
        run: |
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git fetch origin $GITHUB_BASE_REF
            git checkout -b pr
            git checkout $GITHUB_BASE_REF
            git merge --allow-unrelated-histories pr
            yarn test 
        if: github.event_name == 'pull_request'

      - name: Test
        run: |
          yarn test
        if: github.event_name != 'pull_request'