name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Run test over the merged changes
        run: |
            git checkout $GITHUB_BASE_REF
            git merge $GITHUB_HEAD_REF
            yarn test 
        if: github.event_name == 'pull_request'

      - name: Test
        run: |
          yarn test
        if: github.event_name != 'pull_request'