name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn lerna run build

      - name: Run test
        run: yarn test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
